name: skytrack
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10
  lottie: ^3.1.2
  intl: ^0.19.0 
  assets:
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - utils/images/
    

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "utils/images/logo.png"