// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2Hw_5By5SU-ic6gxi7nL0og_WrKDXjRI',
    appId: '1:956647038770:web:d6e8d920bafa222398012b',
    messagingSenderId: '956647038770',
    projectId: 'skytrack-d8fd5',
    authDomain: 'skytrack-d8fd5.firebaseapp.com',
    storageBucket: 'skytrack-d8fd5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAxIkJUYKos7fP5dvbeEEC4sa__U7Ayd0',
    appId: '1:956647038770:android:f62ca7e9eb63489898012b',
    messagingSenderId: '956647038770',
    projectId: 'skytrack-d8fd5',
    storageBucket: 'skytrack-d8fd5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsadUuni38SrGsOT_NDcFQGHWFSATRGhE',
    appId: '1:956647038770:ios:d54936fb84c2b41598012b',
    messagingSenderId: '956647038770',
    projectId: 'skytrack-d8fd5',
    storageBucket: 'skytrack-d8fd5.firebasestorage.app',
    iosBundleId: 'com.example.skytrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsadUuni38SrGsOT_NDcFQGHWFSATRGhE',
    appId: '1:956647038770:ios:d54936fb84c2b41598012b',
    messagingSenderId: '956647038770',
    projectId: 'skytrack-d8fd5',
    storageBucket: 'skytrack-d8fd5.firebasestorage.app',
    iosBundleId: 'com.example.skytrack',
  );
}
